FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./data_pipeline.py ./data_pipeline.py
COPY ./stocks_fastapi.py ./stocks_fastapi.py

COPY ./utils ./utils

CMD ["uvicorn", "stocks_fastapi:app", "--host", "0.0.0.0", "--port", "8010"]